### PR TITLE
[RHCLOUD-19345] Full test coverage

### PR DESCRIPTION
**Pull request by adamrdrew**
This PR adds full test coverage for the entire public API of this library. 

A bit about my testing strategy to explain how things are set up. I believe in testing the API, not what people do with the API. The goal of the tests are to establish that the code as written does what it is supposed to do vis a vis input, output, and errors. So you'll see I removed the sort of end-to-end user story style tests we had and replaced it with lots of little unit tests, each that focus on an individual public methods. I verify that for any method and any given input we get the output we expect, and for any given malformed input we get the error we expect.

Typically my goal is to write an explicit test for each public method. However, the way this lib is constructed makes that a little weird. We have multiple public methods (`ValidateJWTHeaderRequest`, `ValidateJWTCookieRequest`, `ValidateJWTToken`, etc) that are abstracted away behind another public method: `ProcessRequest`. `ProcessRequest` is highly conditional (it acts as a router), thus so long as we test all conditions of `ProcessRequest` we test all public methods it abstracts. I don't know what clients do with this lib, but if those methods are de facto private we may want to make them private in a future release.

Net/Net this patch should provide test coverage for every public code path in this lib. If I missed anything let me know and I'll add it!

### CODE REVIEW

**Comment by adamrdrew** [comment]
Oh something else worth noting: I removed the key generation from the make file and added public and private keys as well as many other files under `test_files`. Testing this lib requires a lot of resources: public and private keys, json examples, a JWT token. It makes sense to me to just provide known good exemplars of these data with the code. Considering the JWT section requires a known public key that matches the encoded token it doesn't make sense to generate that on fly, so we need to include a key. And since we're including a key anyway might as well use that instead of generate one too.

**Comment by adamrdrew** [comment]
Oh, another thing worth noting! This patch makes a minor change to the lib to allow for mocking HTTP requests. There's a new deps module that exports `&http.Client{}` on a public variable and a new `HTTPClient`interface. The lib code uses these now but the change is totally transparent - nothing changed except how we refer to the HTTP client or what type we use for passing around a client. The advantage is we can totally mock out HTTP requests without making deep changes to library composition.

**Review by BlakeHolifield — APPROVED** [review]

**Comment by psav** [comment]
OK - apologies for the length of time on this one, it took me a little while to understand what was going on. I understand why you have modified it, and I agree with it, I do think we lose a little readability here in not configuring the Validator to point to the mocked server we set up. There is definitely some magic in the thinking which we should document. The fact that we override the default http client and add a layer in here is something I have always tried to avoid, but as I said, I agree with it and I'm all for the change.

My only proposal is to change a little how we create the mocked objects. Currently there is a lot of boilerplate code that is perhaps unnecessary. 

```
type Mocker struct {
    func *func() (*http.Response, err)
    getFunc *func(string) (*http.Response, err)
    doFunc *func(*http.Request) (*http.Response, err)
}

func (m *Mocker) Do(req *http.Request){
	if m.doFunc == nil{
		return e.func(req)
	}
	return m.doFunc(req)
}

func (m *Mocker) Get(url string){
	if m.getFunc == nil{
		return e.func(req)
	}
	return m.getFunc(req)

}

func mockResp(req *http.Request) *http.Response {
	io, _ := os.Open("test_files/test_user.json")
	resp := http.Response{
		Body:       io,
		StatusCode: 200,
	}
	return &resp
}

test......{
	emu := Mocker{func: mockResp}
	emu.Do(req)
	emu.Get(req)
}
```

This way, the mocker funcs are much smaller to read contextually, and you can see what is being passed in, you _could_ even pass them in as special funcs inline to a test.

**Review by psav — COMMENTED** [review]
Please look at the comment - mostly great - just a little question to improve and set us a precedence.

**Comment by adamrdrew** [comment]
Dude I LOVE that approach. Still working on thinking idiomatic go and with composition instead of straight OOP. I will rememeber this approach.

**Pull request merged**
